version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  myapp:
    build: .
    container_name: myapp
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./path/to/app:/app

volumes:
  mongodb_data:
    driver: local
